### ISSUE TITLE
JdbcTemplate bean required

### ISSUE THREAD

**Issue by eduardongarcia** [osvaldjr/easy-cucumber#13]
**Describe the bug**
When I try to use only steps about security context, the execution crashes requiring jdbcTemplate bean

**To Reproduce**
1. A project with default config
2. Create a scenario using only security steps
3. Try to run tests
```
Field jdbcTemplate in io.github.osvaldjr.usecases.DatabaseTableSelectUseCase required a bean of type 'org.springframework.jdbc.core.JdbcTemplate' that could not be found.
        - Bean method 'easyCucumberJdbcTemplate' in 'DatabaseConfig' not loaded because @ConditionalOnBean (names: easyCucumberDataSource; SearchStrategy: all) did not find any beans
        - Bean method 'jdbcTemplate' not loaded because @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) did not find any beans
```

**Expected behavior**
The scenario should be executed with success

**Additional context**
easy.cucumber version: 0.0.16
Java version: 1.8.0_144, vendor: Oracle Corporation
Apache Maven 3.5.3
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"

**Comment by LVCarnevalli** [comment]
Corrigido na versão 1.0.0 com divisão de módulos.
